siwon-school/CustomWorldcup_Back

app.js, routes/index.js, routes/worldcup.routes.js
style: router 연결을 index.js로 옮김
=> style: router 연결을 index.js로 옮김

controllers/comments.controller.js, repositories/comments.repository.js, routes/comment.routes.js, services/comments.service.js
body: comment 기본적인 crud 기능 뼈대 완성 다만 아직 다른 service를 이용하는 발리데이션 부분 미작성
=> feat: comment 기본 crud 기능 완성

controllers/worldcup.controller.js, repositories/worldcup.repository.js, routes/worldcup.routes.js, services/worldcup.service.js
feat: GET, PUT, DELETE API 완료
authentication 없이 API 구현 완료 했습니다!
=> feat: GET, PUT, DELETE API 완료

__tests__/unit/controllers/mypage.controller.unit.spec.js, __tests__/unit/repositories/worldcup.repository.unit.spec.js, __tests__/unit/repositories/worldcup_choice.repository.spec.js, __tests__/unit/services/mypage.service.unit.spec.js
unit 하위 폴더로
controllers, services, repositories 추가
+주석 몇 개 변경
=> [Rename] __tests__ unit 폴더 구조 변경

controllers/joi.js, controllers/worldcup.controller.js
feat: joi validation message 추가
이전 PR에서 까먹었습니다....
=> feat: joi validation message 추가

controllers/comments.controller.js, controllers/likes.controller.js, repositories/likes.repository.js, repositories/worldcup.repository.js, routes/like.routes.js, services/likes.service.js
다만 아직 user 정보에 따른 validation은 미작성
=> feat: 좋아요 기능 및 worldcup 존재 여부 확인 기능 구현 완료

__tests__/unit/repositories/worldcup.repository.unit.spec.js, app.js, controllers/joi.js, controllers/worldcup.controller.js, middlewares/error-handler.js, repositories/worldcup.choice.repository.js, repositories/worldcup.repository.js, services/worldcup.service.js
refactor: error handler middleware 추가, 에러 수정 등등
=> refactor: error handler middleware 추가

controllers/comments.controller.js, controllers/joi.js, controllers/likes.controller.js, services/likes.service.js
feat: joi 적용, 좋아요 transaction 적용 await 빼먹은거 다시추가
=> feat: joi 적용, 좋아요 transaction 적용 await 빼먹은거 다시추가

app.js, config/config.js, migrations/20230506065830-create-tokens.js, models/index.js, models/tokens.js
feat: tokens model 생성 및 config file 수정
=> feat: tokens model 생성 및 config file 수정

controllers/users.controller.js, middlewares/auth-middleware.js, package.json, repositories/tokens.repository.js, repositories/users.repository.js, routes/auth.routes.js, services/users.service.js
회원가입, 로그인, 인증 미들웨어 구현하였습니다
기능 먼저 pr해놓고 리팩토링과 로그아웃 진행할 예정입니다
=> feat: 로그인/인증 기능 구현하였습니다 #4

controllers/comments.controller.js, routes/comment.routes.js, routes/like.routes.js
feat: 유저정보 확인 후 comment, like 요청 진행 validation 추가
=> feat: 유저정보 확인 후 comment, like 요청 진행 validation 추가

middlewares/auth-middleware.js
fix: auth-middleware error #7
월드컵 게시물 관련 API 완료
=> fix: auth-middleware error #7

controllers/comments.controller.js, controllers/likes.controller.js, repositories/comments.repository.js, repositories/likes.repository.js, services/comments.service.js, services/likes.service.js
1.좋아요 기능 구현시 request message 전달 안되는 것 수정
2. comment 수정, 삭제 시 해당하는 유저 validate 오류 해결
=> feat: 좋아요, comment validation 오류 해결

middlewares/auth-middleware.js
=> feat: 여기에 내용 #4

middlewares/auth-middleware.js
=> feat:변수 오타 수정 #4

repositories/worldcup.repository.js, services/worldcup.service.js
=> feat: worldcup 예외처리 추가했습니다 #7

__tests__/unit/services/worldcup.service.unit.spec.js, repositories/worldcup.repository.js, services/worldcup.service.js
refactor: GET worldcup - repository findOne(), findAll() 리팩토링 #7
findOne()과 findAll() 안에서 include를 사용해서 테이블들을 join하였습니다. 쿼리신 동환님 감사합니당........
=> refactor: GET worldcup - repository findOne(), findAll() 리팩토링 #7

services/worldcup.service.js
chore: POST allWorldcups Response 변경
프론트에서 요청 주셔서 변경했습니다. 바로 배포 pull 부탁드려요!
=> chore: POST allWorldcups Response 변경

controllers/users.controller.js, routes/auth.routes.js
=> feat : 이메일 인증 1차 임시커밋

__tests__/unit/services/worldcup.service.unit.spec.js, routes/worldcup.routes.js, services/worldcup.service.js, swagger-output.json
chore: worldcup GET 요청 swagger 수정
=> chore: worldcup GET 요청 swagger 수정

__tests__/unit/controllers/comments.controller.unit.spec.js, app.js, controllers/comments.controller.js, controllers/joi.js
[feat: cors 설정 추가, joi 스키마 추가](https://github.com/siwon-school/CustomWorldcup_Back/commit/9240de6815b4ec8cbc1c6e79ee7bebe77b3e6fb4)
=> feat: cors 설정 추가, joi 스키마 추가

controllers/users.controller.js, middlewares/auth-middleware.js, repositories/tokens.repository.js
[fix: auth-middleware console에 찍기](https://github.com/siwon-school/CustomWorldcup_Back/commit/6271a220f9dbfe91eb4a4461ff0ac69d81c300b3)
=> feat: add log

controllers/users.controller.js
[[feat: cors 설정 추가, joi 스키마 추가](https://github.com/siwon-school/CustomWorldcup_Back/commit/9240de6815b4ec8cbc1c6e79ee7bebe77b3e6fb4)](feat: add body refreshtoken)
=> feat: add body refreshtoken

app.js, config/config.js, middlewares/auth-middleware.js, middlewares/error-handler.js, package-lock.json, package.json
feat: Sentry 에러 로그 확인 사이트 연동
에러 로그들을 sentry로 같이 확인하면 좋을 것 같습니다.
이메일 주소 알려주시면 추가하겠습니다. 
https://velog.io/@c1madang/-Sentry
=> feat: Sentry 에러 로그 확인 사이트 연동

controllers/comments.controller.js, controllers/worldcup.controller.js, swagger-output.json, utils/swagger.js
fix: joi validation validateAsyn()를 validate()로 변경 - comments & worldcups controller
=> fix: joi validation validateAsyn()를 validate()로 변경 - comments & worldcups controller

middlewares/auth-middleware.js
테스트하실때 헤더스 주석처리하고 쿠키스 주석 제거해주시면됩니다
=> add:백엔드용 auth-middleware req cookies추가

controllers/worldcup.controller.js
=> fix: update worldcup 오류 수정

controllers/users.controller.js, controllers/worldcup.controller.js, middlewares/error-handler.js, repositories/worldcup.choice.repository.js, repositories/worldcup.repository.js, routes/worldcup.routes.js, services/worldcup.service.js
=> feat: 월드컵 결과 조회 API
